export default class ActionTypes {
  // USERS
  static GET_CONTENT = "GET_CONTENT";
  static GET_EVENTS_LIST = "GET_EVENTS_LIST";
  static GET_EVENT = "GET_EVENT";
  static GET_SERMONS = "GET_SERMONS";
  static GET_SERMON = "GET_SERMON";
  static GET_SERMONS_TYPE = "GET_SERMONS_TYPE";
  static GET_SACRAMENTS = "GET_SACRAMENTS";
  static GET_OVERSEAPARTNERS = "GET_OVERSEAPARTNERS";
  static GET_MINISTERIES = "GET_MINISTERIES";
  static GET_ALL_SERMONS = "GET_ALL_SERMONS";
  static GET_BLOGS = "GET_BLOGS";
  static GET_BLOG = "GET_BLOG";
  static SEND_CONTENT_REQUEST = " SEND_CONTENT_REQUEST";
  static SEND_CONTACT_US_REQUEST = " SEND_CONTACT_US_REQUEST";
  static GET_DONATION_INFO = " GET_DONATION_INFO";
  static GET_EXPLORE_INFO_ALL = " GET_EXPLORE_INFO_ALL";
  static GET_EXPLORE_INFO = " GET_EXPLORE_INFO";
  // SERVICES
}
