export default class ActionTypes {
  // USERS
  static GET_CONTENT = "GET_CONTENT";
  static UPDATE_CONTENT = "UPDATE_CONTENT";
  static CREATE_CONTENT = "CREATE_CONTENT";
  static ADMIN_LOGIN = "ADMIN_LOGIN";
  static LOGOUT = "LOGOUT";
  // EVENTS
  static GET_EVENTS_LIST = "GET_EVENTS_LIST";
  static GET_EVENT = "GET_EVENT";
  static UPDATE_EVENT = "UPDATE_EVENT";
  static CREATE_EVENT = "CREATE_EVENT ";
  static DELETE_EVENT = "DELETE_EVENT";
  // SERMONS
  static GET_SERMONS = "GET_SERMONS";
  static GET_SERMON = "GET_SERMON";
  static UPDATE_SERMON = "UPDATE_SERMON";
  static CREATE_SERMON = "CREATE_SERMON";
  static DELETE_SERMON = "DELETE_SERMON";
  static GET_SERMONS_TYPE = "GET_SERMONS_TYPE";

  // BLOGS
  static CREATE_BLOGS = "CREATE_BLOGS";
  static DELETE_BLOG = "DELETE_BLOG";
  static UPDATE_BLOG = "UPDATE_BLOG";
  static GET_BLOGS = "GET_BLOGS";
  static GET_BLOG = "GET_BLOG";

  static GET_SACRAMENTS = "GET_SACRAMENTS";
  static GET_ALL_SERMONS = "GET_ALL_SERMONS";

  static GET_OVERSEAPARTNERS = "GET_OVERSEAPARTNERS";
  static CREATE_OVERSEAPARTNER = "CREATE_OVERSEAPARTNER";
  static DELETE_OVERSEAPARTNER = "DELETE_OVERSEAPARTNER";
  static UPDATE_OVERSEAPARTNER = "UPDATE_OVERSEAPARTNER";
  static GET_OVERSEAPARTNER = "GET_OVERSEAPARTNER";

  static GET_MINISTERIES = "GET_MINISTERIES";
  static CREATE_MINISTERIES = "CREATE_MINISTERIES";
  static DELETE_MINISTRY = "DELETE_MINISTRY";
  static UPDATE_MINISTRY = "UPDATE_MINISTRY";
  static GET_MINISTERY = "GET_MINISTERY";

  static SEND_CONTENT_REQUEST = " SEND_CONTENT_REQUEST";
  static SEND_CONTACT_US_REQUEST = " SEND_CONTACT_US_REQUEST";
  static GET_DONATION_INFO = " GET_DONATION_INFO";
  static GET_EXPLORE_INFO_ALL = " GET_EXPLORE_INFO_ALL";
  static GET_EXPLORE_INFO = " GET_EXPLORE_INFO";
  // SERVICES
}
